version: '3'
services:
  backend:
    # "build" is reference to locate Dockerfile
    build:
      context: .
      target: ${NODE_ENV}
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - C:/Users/omkar/Desktop/node-app:/app # to map the changes done in host machine and container
    restart: always # restarts the container if it goes down
    # networks:
    #   - docker-network
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    # networks:
    #   - docker-network
    ports:
      - 27017:27017

# networks:
#   docker-network:


# NOTE:
# If you don't specify any network the "compose" will automatically assign them to same network
